Add Docker build
Mudlet/mudlet-package-repo pull request #54
Opened 2020-05-24 12:39 UTC by vadi2

#### Brief overview of PR changes/additions
Add a docker-compose build.
#### Motivation for adding to package repo
Easier setup - don't have to configure all of the dependencies manually. Maybe we can get rid of fakeSMTP and use mailgun for everything as well? The developer would need to setup their own mailgun account then.
#### Other info (issues closed, discussion etc)

2020-05-25 08:37 UTC, Edru2 commented on README.md
> +* `luarocks install lua-mailgun`
```suggestion
* `luarocks install mailgun`
```

2020-05-25 08:40 UTC, Edru2 commented
I installed Docker and Docker-compose, but how to use it?
Maybe we should specify that in the readme.

2020-05-25 11:06 UTC, vadi2 commented
Yeah that's weird, I did add it there - not sure where it went again. It's there now, try again!

2020-05-25 12:02 UTC, Edru2 commented on config.lua
> +
```suggestion
local config = require("lapis.config")
```

2020-05-25 13:27 UTC, Edru2 commented
I have some  problems with getting the server to work with docker.

- I had to remove my postgresql installation to get it up, otherwise the installations collided somehow

- sometimes (cannot reproduce it every time) when I start docker (docker-compose up) the server won't start and I get ```mudlet-package-repo_package-repo_1 exited with code 1``` multiple times.
this is only solvable (some times) by deleting the data folder and rebuilding the docker (docker-compose build). I tried (as Vadi suggested) to change the data folder name for the database but that didn't really solve the problem.

- even if the server works in the docker environment I have problems with sending the email verification. When I register a new user I get an error ```connect failure: connection refused```

2020-05-25 13:34 UTC, vadi2 commented
> I had to remove my postgresql installation to get it up, otherwise the installations collided somehow

If you remove the `ports` line for postgresql, does it fix the problem and does it still work?

2020-05-25 13:42 UTC, Edru2 commented
> If you remove the `ports` line for postgresql, does it fix the problem and does it still work?

That seems to solve the issue!

2020-05-25 15:13 UTC, Edru2 commented
>     * even if the server works in the docker environment I have problems with sending the email verification. When I register a new user I get an error `connect failure: connection refused`
>       Edit: The email verification issue only occurs if the server is started in docker

using mailgun also works in docker environment.

Notice that in order to get mailgun to work it is necessary to add username and password to mail.lua in mail_handler.new part

2020-05-25 15:17 UTC, Edru2 requested changes

2020-05-25 15:17 UTC, Edru2 commented on docker-compose.yml
> +      - 5432:5432
```suggestion
```
Makes it able to use already install postgres together with docker postgres at the same machine

2020-05-25 15:17 UTC, Edru2 commented on Dockerfile
> +CMD mkdir data && lapis migrate $LAPIS_ENVIRONMENT && lapis server $LAPIS_ENVIRONMENT
```suggestion
CMD lapis migrate $LAPIS_ENVIRONMENT && lapis server $LAPIS_ENVIRONMENT
```

2020-05-26 18:36 UTC, demonnic approved these changes

2020-05-26 18:36 UTC, merged